### ISSUE TITLE
Harmony instead of or additionally to a-tisket

### ISSUE THREAD

**Issue by quantenzitrone** [Lioncat6/SAMBL#2]
i kinda like harmony more because it also uses tidal and beatport and is open-source

https://harmony.pulsewidth.org.uk/
https://github.com/kellnerd/harmony/

**Comment by Lioncat6** [comment]
This should be pretty easy to implement so I'll definitely work on this! Thanks for the suggestion lol

**Comment by Lioncat6** [comment]
I'll most likely add a second button for harmony

**Comment by Lioncat6** [comment]
Update: Working on it

**Comment by Lioncat6** [comment]
Done!
![image](https://github.com/user-attachments/assets/8b0e615c-b3ef-4913-89f4-86bad1c2c92e)

The filter list is actually functional now as well!
![image](https://github.com/user-attachments/assets/5aa393c5-ccda-469b-91c7-a906dbee1a67)
