### ISSUE TITLE
Use category URL parameter instead of specifying providers individually

### ISSUE THREAD

**Issue by nimuxoha** [Lioncat6/SAMBL#7]
See https://community.metabrainz.org/t/harmony-music-metadata-aggregator-and-musicbrainz-importer/698641/113

**Comment by Lioncat6** [comment]
Done! Thanks for reporting! https://github.com/Lioncat6/SAMBL/commit/26573c6fef7430e2016541885c8e14eff418c83b

**Comment by Lioncat6** [comment]
Small update to this: Harmony URL parameters are now configurable! 

![Image](https://github.com/user-attachments/assets/d541b2fc-8ea4-44b2-93a7-c79b5f7d439e)
